/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as ProteccaoRouteImport } from './routes/proteccao'
import { Route as RegistarRouteImport } from './routes/registar'
import { Route as VerificarRouteImport } from './routes/verificar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteccaoRoute = ProteccaoRouteImport.update({
  id: '/proteccao',
  path: '/proteccao',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistarRoute = RegistarRouteImport.update({
  id: '/registar',
  path: '/registar',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/pesquisa': typeof PesquisaRoute
  '/proteccao': typeof ProteccaoRoute
  '/registar': typeof RegistarRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/pesquisa': typeof PesquisaRoute
  '/proteccao': typeof ProteccaoRoute
  '/registar': typeof RegistarRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/pesquisa': typeof PesquisaRoute
  '/proteccao': typeof ProteccaoRoute
  '/registar': typeof RegistarRoute
  '/verificar': typeof VerificarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/painel' | '/pesquisa' | '/proteccao' | '/registar' | '/verificar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel' | '/pesquisa' | '/proteccao' | '/registar' | '/verificar'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/pesquisa'
    | '/proteccao'
    | '/registar'
    | '/verificar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRoute
  PesquisaRoute: typeof PesquisaRoute
  ProteccaoRoute: typeof ProteccaoRoute
  RegistarRoute: typeof RegistarRoute
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteccao': {
      id: '/proteccao'
      path: '/proteccao'
      fullPath: '/proteccao'
      preLoaderRoute: typeof ProteccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registar': {
      id: '/registar'
      path: '/registar'
      fullPath: '/registar'
      preLoaderRoute: typeof RegistarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRoute,
  PesquisaRoute: PesquisaRoute,
  ProteccaoRoute: ProteccaoRoute,
  RegistarRoute: RegistarRoute,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
